### ISSUE TITLE
feature: as a user I don't want to have to select the right generated output folder each time

### ISSUE THREAD

**Issue by binary1230** [IsoFrieze/DiztinGUIsh#66]
annoying that Diz prompts you each time for the location of the generated output.

it should just be a text field in the "Export Disassembly" dialog box, with a browse button next to it. 

then, make sure this gets saved correctly with the project settings and as a relative path so user doesn't have to think about it after setting it up one time.

**Comment by ChristopheF** [comment]
I fully agree! And this is also true for all settings that the user can choose, they should all be stored in the project so you don't have to set them each time you open Diz, like:
- the output assembly line format, number of bytes per line, single file/one file per bank
- the checkboxes in the Tools menu (Constants / Options)
- the label list window status (opened or closed)

**Comment by binary1230** [comment]
fixed a bunch of this recently, especially the path saving stuff.

**Comment by binary1230** [comment]
and, I just checked in even more fixes to make this less annoying the first time you start a new project.  clicking "yes" on everything results in good default settings now and creating an 'export' folder for you. and fixed some more bugginess
