### ISSUE TITLE
tracelog not working

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [IsoFrieze/DiztinGUIsh#78]

**Comment by H-A-M-G-E-R** [comment]
live tracing is dont work

**Comment by binary1230** [comment]
One new thing to try, are you running any apple services like itunes etc? I
think I discovered recently that there's a port conflict. Let me know if
disabling apple stuff helps resolve it

**Comment by H-A-M-G-E-R** [comment]
follow the tutorial
